Repository durgesh2001/hacktoberfest_demo, pull requests merged in 2022-10, with the labels that each got.

#53 Added some comments
  Linked_List.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#51 added two new mini web projects
  web-projects/1st project blurr_image/index1.html
  web-projects/1st project blurr_image/script1.js
  web-projects/1st project blurr_image/style1.css
  web-projects/2nd project slider/inedx2.html
  web-projects/2nd project slider/script2.js
  web-projects/2nd project slider/style2.css
Labels: help wanted, hacktoberfest2022, hacktoberfest-accepted

#34 Create quickSort.cpp
  maxHeap.py
  quickSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 Create Next Permutation.java
  Next Permutation.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#50 Added Kadane's algo
  Kadane's-Algorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#48 Create Palindrome.cpp
  Palindrome.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#49 Create Parenthesis Checker.cpp
  Parenthesis Checker.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#43 Create Wildcard Matching.java
  Wildcard Matching.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 added bubble sort code
  BubbleSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#47 Updated today newly Fibonacci.cpp
  Fibonacci.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 Create closestnumbertozero.cpp
  closestnumbertozero.cpp
  kadane.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Famous Problem
  0_1_Knapsack.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 Create Longest Valid Parentheses.java
  Longest Valid Parentheses.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#54 Added hungarianAlgorithm.cpp
  hungarianAlgorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#66 Binary tree traversals
  Binary Tree Traversals
  Fibonacci.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#63 Readme file created
  Binary_search.java
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 added toposort code using DFS
  ShortestWeightedPath.cpp
  ToposortDFS.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 Create Search Insert Position.java
  Search Insert Position.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#61 Create Fractional Knapsack.cpp
  Fractional Knapsack.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#58 Create Overlapping_intervals.cpp
  Overlapping_intervals.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#59 Create Next Greater Element.cpp
  Next Greater Element.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#77 Add files via upload
  strongly-connected-components.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#79 added code for k-knights
  k-knights.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#78 Flood Fill Algorithm C++ | Leetcode #733
  Graph Questions/Flood Fill Algorithm C++ | Leetcode #733
  Graph Questions/Number Of Islands | Leetcode #200
  Graph Questions/Number of Provinces | Leetcode #547
  Graph Questions/Surrounded Regions | Leetcode #130
  Graph Questions/Topological Sort using BFS and DFS | GFG Practice
Labels: hacktoberfest2022, hacktoberfest-accepted

#29 Create Avl_Tree.c
  Avl_Tree.c
Labels: hacktoberfest-accepted

#31 Create Closest_Number_to_Zero.cpp
  Closest_Number_to_Zero.cpp
Labels: hacktoberfest-accepted

#35 Binary to Decimal Conversion
  binToDec.cpp
Labels: hacktoberfest-accepted

#42 ClosestElementTOZero
  ClosetToZero.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#83 Devesh1602 hacktoberfest
  Next Permutation Arrays
Labels: hacktoberfest2022, hacktoberfest-accepted

#87 Created encryption algorith.
  EncryptionAlgo.cpp
Labels: hacktoberfest-accepted

#86 Create interpolation_search.cpp
  Binary_Search_iterative.py
  interpolation_search.cpp
Labels: hacktoberfest-accepted

#85 Kosaraju's Algorithm
  Graph Questions/Alien_Dictionary.cpp
  Kosaraju_algo.cpp
Labels: hacktoberfest-accepted

#84 SkyLine Problem || Famous Interview Question
  SkyLineProblem .py
Labels: hacktoberfest2022, hacktoberfest-accepted

#81 Create HelloWorld.java
  HelloWorld.java
Labels: hacktoberfest, hacktoberfest-accepted

#70 Create Radix_Sort.cpp
  Radix_Sort.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#46 Create Kadane Algorithm.cpp
  Kadane Algorithm.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#40 Create Next Permutation.java
  Next Permutation.java
Labels: hacktoberfest2022

#56 Create Job_Sequence_Problem.cpp
  Job_Sequence_Problem.cpp
Labels: hacktoberfest, hacktoberfest2022

#57 kadanes.cpp
  kadanes.cpp
Labels: hacktoberfest2022

#82 Temp Code Runner File
  tempCodeRunnerFile.cpp
Labels: hacktoberfest-accepted

#80 added code for sudoku problem in cpp
  Sudoku.cpp
Labels: hacktoberfest, hacktoberfest2022

#73 Create sallary_counter.cpp
  sallary_counter.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#71 Adding a dragon game using HTML<CSS<JS
  web-projects/JavaScript Dragon Game/bg.png
  web-projects/JavaScript Dragon Game/bg1.gif
  web-projects/JavaScript Dragon Game/dino.png
  web-projects/JavaScript Dragon Game/dragon.png
  web-projects/JavaScript Dragon Game/gameover.mp3
  web-projects/JavaScript Dragon Game/index.html
  web-projects/JavaScript Dragon Game/music.mp3
  web-projects/JavaScript Dragon Game/script.js
  web-projects/JavaScript Dragon Game/style.css
Labels: hacktoberfest-accepted

#69 fix : #68
  priorityqueue.cpp
Labels: hacktoberfest

#67 Kadanehacktoberfest
  Kadane's.cpp
  kadane's.cpp
Labels: hacktoberfest2022

#55 create tower_of_hanoi
  tower_of_hanoi.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#88 Password Generator in Python
  Password Generator in Python
Labels: hacktoberfest2022, hacktoberfest-accepted

#103 Add files via upload
  DAA Merge sort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#102 added file of first and last occurrence
  firstLastOcc.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#101 Rotten Oranges file added
  Graph Questions/Rotten_Oranges.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#108 adding flutter widget
  drag and drop widget.dart
  fingerprint authentication.dart
  sppeed dial.dart
Labels: hacktoberfest2022, hacktoberfest-accepted

#106 Added Cyclic Sort in java
  CyclicSort.java
Labels: hacktoberfest

#107 Added Drum Play Project
  web-projects/Drum Play/background.jpeg
  web-projects/Drum Play/index.html
  web-projects/Drum Play/script.js
  web-projects/Drum Play/sounds/boom.wav
  web-projects/Drum Play/sounds/clap.wav
  web-projects/Drum Play/sounds/hihat.wav
  web-projects/Drum Play/sounds/kick.wav
  web-projects/Drum Play/sounds/openhat.wav
  web-projects/Drum Play/sounds/ride.wav
  web-projects/Drum Play/sounds/snare.wav
  web-projects/Drum Play/sounds/tink.wav
  web-projects/Drum Play/sounds/tom.wav
  web-projects/Drum Play/style.css
Labels: hacktoberfest-accepted

#105 Reverse a Linked List in groups of any size
  Reverse a Linked List in groups of any size
Labels: hacktoberfest2022, hacktoberfest-accepted

#99 Added Solutions to CSES Introductory Problems
  Burst_Balloons.cpp
  Introductory_Problems/Apple_Division.cpp
  Introductory_Problems/Bit_Strings.cpp
  Introductory_Problems/Coin_Piles.cpp
  Introductory_Problems/Creating_Strings.cpp
  Introductory_Problems/Gray_Code.cpp
  Introductory_Problems/Increasing_Array.cpp
  Introductory_Problems/Missing_Number.cpp
  Introductory_Problems/Number_Spiral.cpp
  Introductory_Problems/Palindrome_Reorder.cpp
  Introductory_Problems/Permutations.cpp
  Introductory_Problems/Repetitions.cpp
  Introductory_Problems/Tower_Of_Hanoi.cpp
  Introductory_Problems/Trailing_zeros.cpp
  Introductory_Problems/Two_Knights.cpp
  Introductory_Problems/Two_Sets.cpp
  Introductory_Problems/Weird_Algorithm.cpp
Labels: hacktoberfest

#98 Create sub_array_sum_equals_k.cpp
  sub_array_sum_equals_k.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#97 Create Immediate smaller element.cpp
  Immediate smaller element.cpp
Labels: hacktoberfest2022

#96 Create Smallest number on left.cpp
  Smallest number on left.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#109 Updated Fibonacci.cpp file
  Fibonacci.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#95 Create kth_smallest_element.cpp
  kth_smallest_element.cpp
Labels: hacktoberfest

#110 Add files via upload
  hero animation.dart
Labels: hacktoberfest2022, hacktoberfest-accepted

#94 Create Change Bits.cpp
  Change Bits.cpp
Labels: hacktoberfest2022

#89 DP Important Questions
  DP Important Questions
Labels: hacktoberfest2022

#90 Sudoku Problem
  Sudoku Problem
Labels: hacktoberfest-accepted

#92 Create Count occurrences of a given word in a 2-d array | GFG HARD
  Graph Questions/0 1 matrix
  Graph Questions/Count occurrences of a given word in a 2-d array
  Graph Questions/Dijkstra's Algorithm
Labels: hacktoberfest2022

#93 Create radix_sort.cpp
  circular_queue
  radix_sort.cpp
Labels: hacktoberfest-accepted

#91 Leetcode Reverse Integer Problem Solution
  reverseInteger.cpp
Labels: hacktoberfest

#111 Add files via upload
  neuomorphic widget.dart
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#113 Created Selection_Sort.java
  Selection_Sort.java
Labels: hacktoberfest-accepted

#112 Create travelingsalesman.c
  travelingsalesman.c
Labels: hacktoberfest-accepted

#117 Added Insertion sort in java
  InsertionSort.java
Labels: hacktoberfest2022, hacktoberfest-accepted

#116 Detect_Cycle_in_Undirected_Graph_BFS.cpp file added
  Graph Questions/Detect_Cycle_in_Undirected_Graph_BFS.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#115 Create DecodeWays.cpp
  DecodeWays.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#114 LeetCode 210. Course Schedule II Solution (Topo Sort w/ BFS)
  Course_Schedule_2.cpp
  Graph Questions/Course_Schedule_2.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#119 Added LeetCode 72.Edit Distance Solution (DP-Hard)
  Edit_Distance.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#118 Create Bellman-Ford-Algorithm.cpp
  Graph Questions/Bellman-Ford-Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#127 Balanced_paranthesis.cpp
  Balanced Paranthesis.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted

#125 Create AssignmentProblemGFG.py
  Graph Questions/AssignmentProblemGFG.py
Labels: hacktoberfest2022, hacktoberfest-accepted

#123 Added Find Eventual Safe States | Leetcode
  Graph Questions/Find Eventual Safe States
Labels: hacktoberfest-accepted

#120 Added LeetCode 4. Median of Two Sorted Arrays
  Median_of_Two_Sorted_Arrays.cpp
Labels: hacktoberfest-accepted

#126 Create TowerOfHanoi.java
  TowerOfHanoi.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#124 Added Dijkstra Algorithm in python
  Dijkstra_Algo.py
Labels: hacktoberfest-accepted

#122 Create Trapping_rain_water.cpp
  Trapping_rain_water.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#121 Dijkstra algo (Greedy) file added
  Graph Questions/Dijkstra.cpp
Labels: hacktoberfest2022, hacktoberfest-accepted
